"""
Mock SAP Accounts Payable invoice data.
"""

AP_INVOICES = [
    {
        "invoice_document": "5100001001",
        "vendor_invoice_reference": "INV-OS-1001",
        "business_partner": "BP1000",
        "purchase_order": "4500001001",
        "company_code": "UK01",
        "invoice_date": "2026-07-10",
        "posting_date": "2026-07-12",
        "currency": "GBP",
        "invoice_amount": 12500.00,
        "po_amount": 12500.00,
        "goods_receipt_amount": 12500.00,
        "tax_amount": 2500.00,
        "payment_terms": "30 DAYS",
        "payment_due_date": "2026-08-11",
        "invoice_status": "POSTED",
        "payment_status": "UNPAID",
        "payment_block": False,
        "duplicate_check_status": "UNIQUE",
        "matching_status": "MATCHED",
    },
    {
        "invoice_document": "5100001002",
        "vendor_invoice_reference": "INV-IT-2001",
        "business_partner": "BP2000",
        "purchase_order": "4500001002",
        "company_code": "UK01",
        "invoice_date": "2026-07-15",
        "posting_date": None,
        "currency": "GBP",
        "invoice_amount": 24000.00,
        "po_amount": 24000.00,
        "goods_receipt_amount": 0.00,
        "tax_amount": 4800.00,
        "payment_terms": "14 DAYS",
        "payment_due_date": "2026-07-29",
        "invoice_status": "BLOCKED",
        "payment_status": "NOT_DUE",
        "payment_block": True,
        "duplicate_check_status": "UNIQUE",
        "matching_status": "NOT_MATCHED",
    },
    {
        "invoice_document": "5100001003",
        "vendor_invoice_reference": "INV-EU-3001",
        "business_partner": "BP4000",
        "purchase_order": "4500001003",
        "company_code": "DE01",
        "invoice_date": "2026-07-14",
        "posting_date": None,
        "currency": "EUR",
        "invoice_amount": 48000.00,
        "po_amount": 48000.00,
        "goods_receipt_amount": 24000.00,
        "tax_amount": 9120.00,
        "payment_terms": "45 DAYS",
        "payment_due_date": "2026-08-28",
        "invoice_status": "BLOCKED",
        "payment_status": "NOT_DUE",
        "payment_block": True,
        "duplicate_check_status": "UNIQUE",
        "matching_status": "PARTIAL_MATCH",
    },
    {
        "invoice_document": "5100001004",
        "vendor_invoice_reference": "INV-OS-1001",
        "business_partner": "BP1000",
        "purchase_order": "4500001001",
        "company_code": "UK01",
        "invoice_date": "2026-07-16",
        "posting_date": None,
        "currency": "GBP",
        "invoice_amount": 12500.00,
        "po_amount": 12500.00,
        "goods_receipt_amount": 12500.00,
        "tax_amount": 2500.00,
        "payment_terms": "30 DAYS",
        "payment_due_date": "2026-08-15",
        "invoice_status": "BLOCKED",
        "payment_status": "NOT_DUE",
        "payment_block": True,
        "duplicate_check_status": "DUPLICATE",
        "matching_status": "MATCHED",
    },
    {
        "invoice_document": "5100001005",
        "vendor_invoice_reference": "INV-OS-1005",
        "business_partner": "BP1000",
        "purchase_order": None,
        "company_code": "UK01",
        "invoice_date": "2026-07-17",
        "posting_date": None,
        "currency": "GBP",
        "invoice_amount": 950.00,
        "po_amount": 0.00,
        "goods_receipt_amount": 0.00,
        "tax_amount": 190.00,
        "payment_terms": "30 DAYS",
        "payment_due_date": "2026-08-16",
        "invoice_status": "PARKED",
        "payment_status": "NOT_DUE",
        "payment_block": False,
        "duplicate_check_status": "UNIQUE",
        "matching_status": "NON_PO",
    },
]